/*
Oden API

Testing ScrapYieldDataAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package oden

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/odenio/oden-client-go"
)

func Test_oden_ScrapYieldDataAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ScrapYieldDataAPIService V2ScrapYieldDeletePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.ScrapYieldDataAPI.V2ScrapYieldDeletePost(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ScrapYieldDataAPIService V2ScrapYieldSearchPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.ScrapYieldDataAPI.V2ScrapYieldSearchPost(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ScrapYieldDataAPIService V2ScrapYieldSetPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.ScrapYieldDataAPI.V2ScrapYieldSetPost(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
