/*
Oden API

Testing OQLAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package oden

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/odenio/oden-client-go"
)

func Test_oden_OQLAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OQLAPIService V2OqlQueryPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.OQLAPI.V2OqlQueryPost(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
